version: "3"

services:
  backend:
    image: frappe/erpnext:${ERPNEXT_VERSION:-v15.65.0}
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    platform: linux/arm64
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "${BACKEND_PORT}:8000"

  configurator:
    image: frappe/erpnext:${ERPNEXT_VERSION:-v15.65.0}
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    platform: linux/arm64
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      SOCKETIO_PORT: ${SOCKETIO_PORT}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: frappe/erpnext:${ERPNEXT_VERSION:-v15.65.0}
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    platform: linux/arm64
    command:
      - >
        wait-for-it -t 120 ${DB_HOST}:${DB_PORT};
        wait-for-it -t 120 ${REDIS_CACHE};
        wait-for-it -t 120 ${REDIS_QUEUE};
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=${ADMIN_PASSWORD} --db-root-username=${DB_ROOT_USERNAME} --db-root-password=${DB_ROOT_PASSWORD} --install-app erpnext --set-default ${SITE_NAME};
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SITE_NAME: ${SITE_NAME}

  db:
    image: mariadb:${MARIADB_VERSION:-10.6}
    networks:
      - frappe_network
    healthcheck:
      test: mysqladmin ping -h localhost --password=${MYSQL_ROOT_PASSWORD}
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --port=${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    platform: linux/arm64
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"

  frontend:
    image: frappe/erpnext:${ERPNEXT_VERSION:-v15.65.0}
    networks:
      - frappe_network
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: ${BACKEND_HOST}:${BACKEND_INTERNAL_PORT}
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME}
      SOCKETIO: ${WEBSOCKET_HOST}:${SOCKETIO_PORT}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    platform: linux/arm64
    ports:
      - "${FRONTEND_PORT}:8080"

  queue-long:
    image: frappe/erpnext:${ERPNEXT_VERSION:-v15.65.0}
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - ${QUEUE_LONG,default,short}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    platform: linux/arm64
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  queue-short:
    image: frappe/erpnext:${ERPNEXT_VERSION:-v15.65.0}
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - ${QUEUE_SHORT,default}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    platform: linux/arm64
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  redis-queue:
    image: redis:${REDIS_VERSION:-6.2-alpine}
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data
    ports:
      - "${REDIS_QUEUE_PORT}:6379"
    platform: linux/arm64
    command: redis-server --port 6379

  redis-cache:
    image: redis:${REDIS_VERSION:-6.2-alpine}
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "${REDIS_CACHE_PORT}:6379"
    platform: linux/arm64
    command: redis-server --port 6379

  scheduler:
    image: frappe/erpnext:${ERPNEXT_VERSION:-v15.65.0}
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    platform: linux/arm64
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  websocket:
    image: frappe/erpnext:${ERPNEXT_VERSION:-v15.65.0}
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    platform: linux/arm64
    ports:
      - "${WEBSOCKET_PORT}:9002"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

volumes:
  db-data:
  redis-queue-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
